### ISSUE TITLE
Questions/Help 

### ISSUE THREAD

**Issue by rafamadriz** [RangHo/dotfiles#8]
I saw you post on reddit, I asked a few questions and you were open to answer more of my questions regarding the [script](https://github.com/RangHo/dotfiles/blob/main/dotfile) if I opened an issue here, so here I am. 

* Regarding this line  [here](https://github.com/RangHo/dotfiles/blob/8dfc43927d7c54164c7b32c761827fdf967a9928/dotfile#L434), Is it possible to not prompt for password when making/building the package ? [This](https://github.com/rafamadriz/dotfiles/blob/691e92d7e4d255b3d9aede188dd92ced28e2f296/.local/share/rais/install.sh#L29) is how I'm doing it, since it's not possible run that command with root I have to do it as the user running the script, but I don't want to prompt for password. 
*  I see that you have everything in just one script, how do you handle installing your dotfiles  from this repo? The problem I had was that when cloning the repo and then copying everything to $HOME, it would be copied to the $HOME of the root user, so I had to split the script in two files, one with commands needing root access and then calling the other script as the user running the script, so everything is copied to the correct $HOME folder. You can see it [here](https://github.com/rafamadriz/dotfiles/blob/691e92d7e4d255b3d9aede188dd92ced28e2f296/.local/share/rais/install.sh#L62). The first solution I thought of was putting the script for the user as a function, and then executing that function as the $user. But that was more difficult than what I thought, as explained in [this thread](https://stackoverflow.com/questions/17926153/bash-run-function-with-different-user), apparently I can do something like this 
```
#!/bin/bash
function1(){
   echo `whoami` 
}
export -f function1
su username -c "bash -c function1"
``` 
But that seems very hacky. The second solution I thought to have everything in one single script was using a complete path in this [line](https://github.com/rafamadriz/dotfiles/blob/691e92d7e4d255b3d9aede188dd92ced28e2f296/.local/share/rais/dotScript.sh#L15) for copying everything to $HOME, so I use `/home/$user/` instead and that would install everything in the user's home folder instead of the root user. But what it's your ideal solution for this ? 
* I've also noticed that you have some kind of debugging going on, is that being printed to a file in case there's any error ? Or does it just goes to stdout ? 

Anyway these are the two main questions I have, doing `makepkg -si --noconfirm` without asking for password, and finding some way of having everything in one script file without installing things where they don't go. This is my [script](https://github.com/rafamadriz/dotfiles/tree/main/.local/share/rais), I know it's going to be kinda cringe to look at it, what you're doing seems more complex, elegant and better engineered overall, but hey, mine is getting the job done I just want to improve it and hopefully someday have something similar to yours, so I'm open to any suggestions if you want to see it and tell me ways to improve it. 

In advance, thanks for your time and good luck in the military.

**Comment by RangHo** [comment]
I took a quick peek at your code. It seems like you are calling the script with sudo privilege. Apparently this is considered a *bad practice* as it makes you numb to calling whatever script with sudo but idk... Anyways, here are the answers.

### How to install stuff without typing password a gazillion times
Regardless of whether using `sudo` to call program is a good practice or not, in this case I would recommend actually calling the script as the user you want to install the script. When I take a look at your code, I see you are executing the script with `sudo` and within that script you `sudo` back to the current user. What you are doing is basically using `sudo` to actually *switch user*, instead of *running a command with root privilege*. In this case, `sudo` timeout is ineffective. So, I recommend calling the script itself as the regular user and use `sudo` when absolutely necessary. This way, you don't have to build AUR packages by going back to regular user within a `sudo` environment.

Do not call the entire script as `root` unless absolutely necessary. `sudo` timeout allows you to run `sudo` multiple times without having to input a password multiple times, and being `root` all the time becomes more of a hassle when you have some commands to run as a regular user.

### How to put everything in a single file
The second question can be solved by the first solution as well. This is the case where having `root` privilege becomes a hassle. If the script is not called with `sudo`, you can just `cp` and the file permission and ownership would be fine and dandy. For me, I delegate "installing" files to `GNU stow`, as explained in the README file.

So this is how I implemented my installer:
1. Provide a list of necessary dependencies in `pkginfo` file. In that file, use `depends` command to add a package to the dependency list.
2. The main `dotfile` script will `source` the `pkginfo` definition file. It will execute all the `depends` command where each call will construct a list of depending packages. ~~(haha recursive call go brrr)~~
3. The actual installation function will read the list of packages and install them. Inside the functions I use `sudo` command if necessary.

Since most of them don't take very long time, in most cases I don't have to provide `sudo` password more than one time. If you have massive AUR packages built (like linux kernel) you can use the `sudo` keepalive script I showed in the original Reddit post.

### What are those debug stuffs
The `debug` shenanigan is basically a debug output that you can enable by setting `DEBUG` environment variable to non-null. Check [this line](https://github.com/RangHo/dotfiles/blob/8dfc43927d7c54164c7b32c761827fdf967a9928/dotfile#L9-L10) and [these logging function definitions](https://github.com/RangHo/dotfiles/blob/8dfc43927d7c54164c7b32c761827fdf967a9928/dotfile#L43-L60).

If this answer your question, please close the issue. Or you can ask a follow-up question, if you have more!

**Comment by rafamadriz** [comment]
Thanks I appreciate it!
